variables:
  REGISTRY: quay.io
  NAME: go-keycloak-proxy
  GOVERSION: 1.7.0

stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  image: golang:${GOVERSION}
  before_script:
  - mkdir -p /go/src/github.com/gambol99
  - ln -sf /builds/go/keycloak-proxy /go/src/github.com/gambol99
  - cd /go/src/github.com/gambol99/keycloak-proxy
  script:
  - make deps
  - make test

build:
  stage: build
  image: golang:${GOVERSION}
  before_script:
  - mkdir -p /go/src/github.com/gambol99
  - ln -sf /builds/go/keycloak-proxy /go/src/github.com/gambol99
  - cd /go/src/github.com/gambol99/keycloak-proxy
  script:
  - make deps
  - make static
  artifacts:
    expire_in: 1d
    paths:
    - bin/
  only:
    - master
    - /^v([0-9]{1,3}[.]?){3}.*$/

deploy:
  stage: deploy
  script:
    - export VERSION=$CI_BUILD_REF_NAME
    - '[[ "$VERSION" == "master" ]] && VERSION="latest"'
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN} -e ${REGISTRY_EMAIL} ${REGISTRY}
    - docker build -t ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION} .
    - docker push ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION}
    - docker rmi ${REGISTRY}/${REGISTRY_AUTHOR}/${NAME}:${VERSION}
  only:
    - master
    - /^v([0-9]{1,3}[.]?){3}.*$/
