env:
  global:
  - secure: TNsg6LtrEmf7Q2JxmCR4A7vEapS/ikM4LBTJqhq9k6/ugy2ZlE4I9neXwGQLI/ohCYF1FXV+qg18qXJUzz0dQTZ1Sfma2hVUh2wU5E58J16g7SeubSYLJ79kBAJRYoNOrgWyBHKRSvXvYN6Lj9o+BgZSi5q9q7nlw3oNeY/LuZ9WGUQmK0HQwS0m/bHAfcrsTafWvrILA1d+dHM5YRElDrVOaVy7QOj1mK3aqPyMIS82PBSTwdR27FekDrZKKrHt0DAfARDgOfMyl7Dzfhn26tSBTBwRXVu73bFQGYpa9vUfyKZb6EWYKdhSEdWOCW4Znk98HdPSGRJtXuIVR3K+wbxc0gkCeNLBqZ1QK5aVl96SB8RITQ3Ah/JYczp1gSGGAeW/ov7fgZ0DRUdj8QPxvOxq7V57LbnP3L2M+0KwpYCqpvxPBH5NC6G/T0iOK9v9Om0fk8DcNmws+RYc39JIaYZv+9cmeZf5XrNfN1cPo7wGMIuBzvz6uA+cRYaHgzo1pvwnL2fgNLQEeDjpD7QbFkxj87y3E0D0afS5vC1jgd32GmM+tFkXXhN7mi8mBvnn7IN4PC8SNa4alfyvxwwG+AWcut7fErPZA7EwDAGBEt3j9S9xb6GwqY7fFT+3+2VFXH0mW9KK+p/wT+sigGsFVAQIGjitvR+EzThPvezXDaA=
  - secure: T9f1m49LefUqEW0u6iNjLLrF1xUIaaePjrggScDcVa/wepInuq+gznLsjsDY9U53j5K9iB142IeyZa93n/vHUfSy2Vg1GJRaJt7b0xAPZIyBlTV5dCfIk4QHrMaPhYHiSvlUjYyCk90rf2e+fcUBfQQVLjpXmg4cwNaCV1KIzE3wpZvXJVLXEbx6OMjGbSM7KwmdUMwjEXOszJHtN3W000F5LwxoKeHZqQ2irDRDVPS/Pjt2t5OKoy5KLjeys7p40iUXS0z0JPAukGtJb6QujBBGG9ar/x0nwaP88t0c5BKqHbXY+C9QqsOJLEWLUcR0YUzSdSgfeS2AIaaPkJCt4e6vdsvySjth2Ynfxv6zapwXyxJTDXeKUrBZZWn6lRrMIikUoqpXqnzZvIWkJBHBtkiBPX16xyoONx9cyastL18ggxcR22xaNLRxE7rUmS4jO1yr81MyFIsy7Rk/nyKGooETNNnrL9uY47kPY0cuqobDmfl3C7UFNYsuB2xnprezYM1ivHn6irapqmZdO1v6K191gGwl5P14BcNW3G6jQkSzkrIrQp95Y6hVjcRtaYMFabzhk5vrPAOv4Zk61dzF5EoOddRADqyr88RaajlB/oFJi2c2aA31fCOLES4ES2J+517pd53/RaFP99b+MY/8w+kv6CX/rVesgSFkVu4kwXM=
  - AUTHOR_EMAIL=gambol99@gmail.com
  - REGISTRY_USERNAME=gambol99+rebotbuilder
  - REGISTRY=quay.io
services:
- docker
language: go
go:
- 1.8
install:
- go get github.com/tools/godep
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_EVENT_TYPE} == "push" ]]) || [[ -n ${TRAVIS_TAG} ]]; then
    NAME=GOOS=windows GOARCH=amd64 godep go build -o bin/keycloak-proxy-windows-amd64.exe;
    NAME=GOOS=linux GOARCH=amd64 godep go build -o bin/keycloak-proxy-linux-amd64;
    docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} -e ${AUTHOR_EMAIL} ${REGISTRY};
    VERSION=${TRAVIS_TAG:-latest} make docker-release;
  fi
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: gambol99/keycloak-proxy
    tags: true
  api_key:
    secure: "${GITHUB_TOKEN}"
  file:
  - bin/keycloak-proxy-windows-amd64.exe
  - bin/keycloak-proxy-linux-amd64
