version: 2.0
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:latest-alpine
    environment:
      GO111MODULE: "on"
    working_directory: ~/project
    steps:
      - run:
          name: Install prerequisites for alpine
          command: |
            apk add git openssh-client ncurses
      - checkout
      - run:
          name: Run linter
          environment:
          command: |
            golangci-lint run --deadline 2m --new-from-rev master

  test:
    working_directory: /go/src/github.com/oneconcern/keycloak-gatekeeper
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: GO111MODULE=on go test -v -covermode=atomic -coverprofile=cover.out
          no_output_timeout: 30m

  build_image:
    docker:
      - image: gcr.io/onec-co/depmon-builder:latest
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      REPOSITORY: 'gcr.io/onec-co'
      GOOGLE_PROJECT_ID: onec-co
      GOOGLE_COMPUTE_ZONE: us-west2-c
      IMAGE: gatekeeper
    shell: /bin/bash
    steps:
      - run:
          name: Initialize gcloud sdk
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet config set container/new_scopes_behavior true
            gcloud --quiet container clusters get-credentials ${CLUSTER}
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Prepare environment
          shell: /bin/bash
          command: |
            echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://gcr.io
      - run:
          name: Build tagged docker image then push to gcloud repo
          command: |
            VERSION=$(git describe --tags --exact-match || true)
            SHA1=$(git rev-parse HEAD)
            BUILD=$(date +%s)
            if [[ -n "${VERSION}" ]] ; then
              docker build --progress plain \
              --build-arg TAG=${VERSION} --build-arg SHA1=${SHA1} --build-arg BUILD=${BUILD} \
              -t ${REPOSITORY}/${IMAGE}:${VERSION} \
              -t ${REPOSITORY}/${IMAGE}:latest \
              .
              docker push ${REPOSITORY}/${IMAGE}:${VERSION}
              docker push ${REPOSITORY}/${IMAGE}:latest
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          context: "OC Common"
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - test:
          context: "OC Common"
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - build_image:
          context: "OC Common"
          requires:
            - lint
            - test
          filters:
            tags:
              # ignore tags from original repo, just OneConcern tags
              only: /^v.*-1c/
            branches:
              only: /oneconcern-release/
